### ISSUE TITLE
Tasks for Ian

### ISSUE THREAD

**Issue by aazaff** [ngds/ADEPT_frontend#29]
* [ ] ADEPT - get email credentials into ADEPT pod  #d7aa8b1a
* [ ] Geoparser - run over <some number> of geothermal docs and attach it to some user.  #6a192b3a 
* [ ] ADEPT - don't expire api keys so quickly.  #2a989bd6
* [ ] ADEPT - make sure all products API changes are in prod.  #5d4c143c
* [ ] ADEPT - better error catching in products endpoint.  #eefe6619
